# Generated by Django 5.2.3 on 2025-06-22 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(max_length=60)),
                ('responsavel', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(blank=True, max_length=20, null=True)),
                ('data_fim', models.DateField(max_length=60)),
                ('noetapas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(max_length=30)),
                ('morada', models.CharField(blank=True, max_length=100, null=True)),
                ('nodocident', models.CharField(blank=True, max_length=20, null=True)),
                ('datanasc', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(default='exemplo@dominio.pt', max_length=254, unique=True)),
                ('grade', models.CharField(max_length=50)),
                ('equipa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipa')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.CharField(max_length=100)),
                ('chegada', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('distancia', models.FloatField()),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='api.prova')),
            ],
        ),
        migrations.AddField(
            model_name='equipa',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipas_geridas', to='api.utilizador'),
        ),
    ]
