# Generated by Django 5.2.3 on 2025-06-22 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('notas', models.CharField(max_length=180)),
                ('equipa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipa')),
                ('prova', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prova')),
            ],
        ),
    ]
