# Generated by Django 5.2.3 on 2025-06-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eqprova'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField()),
                ('lugar', models.PositiveIntegerField()),
                ('desclassifica', models.BooleanField(default=False)),
                ('desiste', models.BooleanField(default=False)),
                ('notas', models.CharField(max_length=180)),
                ('ciclista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ciclista')),
                ('etapa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.etapa')),
            ],
        ),
    ]
