# Generated by Django 5.2.3 on 2025-06-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resultados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultados',
            name='notas',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
